### ISSUE TITLE
Add a feature for the huds for "only when OP Menu is visible" as well as if the TM interface is hidden

### ISSUE THREAD

**Issue by CatzHoekk** [XertroV/tm-cotd-hud#2]
Atm the setting 
![image](https://user-images.githubusercontent.com/69237200/224797645-5df00489-2685-494a-90f8-882e945d8c99.png)
actually means "only when OP Menu is visible" and there is no option to hide the hud if the actual tm interface is hidden. Would be neat if that was added.

As inspiration, Grinding Stats solved it with a combo box which i find quite neat. 
![image](https://user-images.githubusercontent.com/69237200/224798008-8e226e27-132d-43be-beaf-524293532f7b.png)

**Comment by XertroV** [comment]
fixed in next version (submitted now). new option added (default true) to hide UI stuff when the game UI is hidden.
